nMonte: 1000

variables:
  r: 
    type: 'range'
    min: 0
    max: 1
    length: 21

  beta:
    type: 'list'
    values: 
      - .8
      - .9

  n_samples:
    type: 'list'
    values:
      - 10000

  sigma:
    type: 'list'
    values:
      - 1.0
