nMonte: 97

variables:
  r:
    min: 0
    max: 3
    length: 25

  beta:
    min: .45
    max: 1
    length: 27

  n_features:
    - 5000

  n_samples:
    - 2000
    - 50000

  Zipf_params:
    - .0
    - 1
    - 2

