nMonte: 2

variables:
  r: 
    min: 0
    max: 2
    length: 3

  beta:
    min: .45
    max: 1
    length: 5

  n_features: 
    - 10000

  n_samples:
    - 5000
    - 10000
    - 50000

  Zipf_params:
    - .0
    - .5

