nMonte: 500

variables:
  r: 
    type: 'range'
    min: 0
    max: 1
    length: 21

  beta:
    type: 'list'
    values: 
      - .5
      - .6
      - .7
      - .8
      - .9

  n_samples:
    type: 'list'
    values:
      - 1000

  sigma:
    type: 'list'
    values:
      - .5
      - 1.0
      - 2.0
